include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'
stages:
  - check
  - test
  - deploy

variables:
    BUNDLE: "authenticator-dev.flatpak"

flatpak:
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
    variables:
        MANIFEST_PATH: "build-aux/com.github.bilelmoussaoui.Authenticator.json"
        FLATPAK_MODULE: "Authenticator"
        MESON_ARGS: "-Dprofile=development"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "com.github.bilelmoussaoui.AuthenticatorDevel"
    extends: .flatpak

review:
    stage: deploy
    dependencies:
        - 'flatpak'
    extends: '.review'

stop_review:
    stage: deploy
    extends: '.stop_review'



flake8:
  stage: check
  script:
    - dnf install -y python3-flake8
    - flake8 --ignore E402,W503 --show-source src/
